[package]
name = "rust-web-sample"
version = "0.1.0"
authors = ["Qi Luo <lunaofscarlet@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.80"
wasm-logger = "0.2.0"
yew = "0.19.3"
